thermal_tol_list = c("Acipenser fulvescens","Alosa chrysochloris","Ameiurus melas","Ameiurus natalis","Ameiurus nebulosus","Amia calva","Aplodinotus grunniens","Campostoma anomalum","Campostoma oligolepis","Carpiodes carpio","Carpiodes cyprinus","Carpiodes velifer","Catostomus catostomus","Catostomus commersoni","Catostomus platyrhynchus","Cottus  bairdii","Couseius plumbeus","Cottus carolinae","Culea inconstans","Cycleptus elongatus","Cyprinella lutrensis","Cyprinella spiloptera","Dorosoma cepedianum","Dorosoma petenese","Erimystax x-punctatus","Esox americanus","Etheostoma blennioides","Etheostoma caeruleum","Etheostoma chlorosoma","Etheostoma exile","Etheostoma flabellare","Etheostoma microperca","Etheostoma nianguae","Etheostoma nigrum","Etheostoma punctulatum","Etheostoma spectabile","Etheostoma zonale","Fundulus sciadicus","Gambusia affinis","Hiodon alosoides","Hybognathus argyritis","Hybognathus hankinsoni","Hybognathus nuchalis","Hybognathus placitus","Hypentelium nigricans","Ichthyomyzon castaneus","Ichthyomyzon fossor","Ictalurus furcatus","Ictalurus punctatus","Ictiobus bubalus","Ictiobus cyprinellus","Ictiobus niger","Labidesthes sicculus","Lepisosteus oculatus","Lepisosteus osseus","Lepisosteus platostomus","Lepomis cyanellus","Lepomis gibbosus","Lepomis gulosus","Lepomis humilis","Lepomis macrochirus","Lepomis megalotis","Lota lota","Luxilus chrysocephalus","Luxilus cornutus","Lythrurus umbratilis","Macrhybopsis aestivalis","Macrhybopsis gelida","Macrhybopsis meeki","Macrhybopsis storeriana","Margariscus margarita","Micropterus dolomieu","Micropterus punctulatus","Micropterus salmoides","Morone chrysops","Morone mississippiensis","Moxostoma carinatum","Moxostoma duquesnei","Moxostoma erythrurum","Moxostoma macrolepidotum","Nocomis biguttatus","Notemigonus crysoleucas","Notropis atherinoides","Notropis blennius","Notropis buchanani","Notropis dorsalis","Notropis greenei","Notropis nubilus","Notropis rubellus","Notropis shumardi","Notropis stramineus","Notropis topeka","Noturus exilis","Noturus flavus","Noturus gyrinus","Noturus nocturnus","Perca  flavescens","Percina caprodes","Percina cymatotaenia","Percina evides","Percina maculata","Percina phoxocephala","Percopsis omiscomaycus","Phenacobius mirabilis","Phoxinus erythrogaster","Pimephales notatus","Pimephales promelas","Pimephales vigilax","Polyodon spathula","Pomoxis annularis","Pomoxis nigromaculatus","Prosopium williamsoni","Pylodictis olivaris","Rhinichthys atratulus","Richardsonius balteatus","Sander canadensis","Sander vitreum","Scaphirhynchus albus","Scaphirhynchus platorynchus","Semolitus atromaculatus","Thymallus arcticus")
setwd('F:/sdm_modeling/spdata')
umn = read.csv('Moore_et_al_2021_Mussel_Lifehistory.csv')
umn_mussel_list = paste(umn$genus,umn$species,sep=" ")
usgs_fish = read.csv('species-listings-by-tax-group-report.csv')
usgs_fish_list = usgs_fish$Scientific_name

sp_list = read.csv('sp_list.csv')#complete list that concatenates all the lists from above.
sp_list = sp_list$species_name

sp_list_new = read.csv('sp_list2.csv') # list that includes natureserve sp. list.